### ISSUE TITLE
BUG REPORT:  v2/v3 Leaving behind unclaimed fee wallet with uncirculated value in old pools and only claiming pool tokens.

### ISSUE THREAD

**Issue by cleancoindev** [bancorprotocol/contracts-v3#376]
Bug that was the same bug in v2 you are doing now to v3?

https://github.com/bancorprotocol/contracts-v3/blob/dev/contracts/network/BancorV1Migration.sol

Your migration is leaving out the fee wallets and leaving behind the unclaimed fees that were never realized gains from the original pools if you do not take the 'claim' into account and claim them.

There are fee wallets that are not the same as the pool token counts if virtual balance is off.

Why have they been ignored in both v2 and now v3?  Is there a specific reason the migration contract is intentionally by design leaving behind the unclaimed fees from the v0/v1 systems? 

This seems like a gross oversight/bug.  Am I wrong here?  Thanks for clarifications.  I'd like a bug bounty if this is a bug/oversight.

**Comment by yudilevi** [comment]
Hey @cleancoindev, I’m not sure I completely understand what you’re referring to, but the value of a v2.1 position - returned by the “removeLiquidityReturn” method - includes the total amount (both the liquidity and the accrued fees). That same value is migrated into v3. Where exactly do you see an issue?

**Comment by yudilevi** [comment]
Closing until further information is provided.
